services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: PRODUCTION
      MONGO_URI: mongodb://mongo:27017/picnic-db
    ports:
      - 10000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - picnic-db:/data/db
    ports:
      - "27017:27017"

volumes:
  picnic-db:
