name: Continuous Integration and Deployment

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install Dependencies, Lint, Test, and Build
        run: |
          npm install
          npm run lint
          npm run test
          npm run build

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
        with:
          args: |
            rsync -avz --exclude 'dist/' --exclude 'node_modules/' --exclude '.env' ./ ${REMOTE_USER}@${REMOTE_HOST}:/usr/src/app
            ssh ${REMOTE_USER}@${REMOTE_HOST} << 'EOF'
              cd /usr/src/app
              docker-compose down
              docker-compose up --build -d
            EOF
